version: "3.9"
name: justedlevhub
services:
  notifications:
    build: .
    container_name: notification-service
    env_file:
      - "C:\Users\edwar\OneDrive\intellij\env\notification-docker.env"
    image: justedlev/notification-service:1.0
    ports:
      - "0:8080"
    depends_on:
      - postgres
      - service-registry