server:
  port: 0
  servlet:
    context-path: /api
  error:
    include-stacktrace: never

spring:
  config:
    import:
      - classpath:/logging.yml
      - classpath:/eureka.yml
      - classpath:/keycloak.yml
      - classpath:/cloudamqp.yml
      - classpath:/springdoc.yml
      - classpath:/management.yml
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
          jwk-set-uri: ${keycloak.jwk-set-uri}
        opaquetoken:
          introspection-uri: ${keycloak.introspection-uri}
          client-id: ${keycloak.client-id}
          client-secret: ${keycloak.client-secret}
  devtools:
    restart:
      enabled: false
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_schema: notifications
  sql:
    init:
      mode: always
  rabbitmq:
    host: ${cloudamqp.host}
    port: ${cloudamqp.port}
    password: ${cloudamqp.password}
    username: ${cloudamqp.username}
    virtual-host: ${cloudamqp.virtual-host}
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    test-connection: false
    username: ${SERVICE_MAIL_EMAIL}
    password: ${SERVICE_MAIL_PASSWORD}
    properties:
      mail:
        debug: ${SERVICE_MAIL_IS_DEBUG:false}
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Custom properties

configuration:
  name: ${spring.application.name}
  email: ${SERVICE_MAIL_EMAIL}
  service:
    url: ${GATEWAY_HOST}/${spring.application.name}${server.servlet.context-path}