server:
  port: 0
  servlet:
    context-path: /api

logging:
  level:
    web: trace
    sql: trace

spring:
  application:
    name: '@project.name@'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
          jwk-set-uri: ${keycloak.jwk-set-uri}
        opaquetoken:
          introspection-uri: ${keycloak.introspection-uri}
          client-id: ${keycloak.client-id}
          client-secret: ${keycloak.client-secret}
  devtools:
    restart:
      enabled: true
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_schema: notifications
  sql:
    init:
      mode: always
  rabbitmq:
    host: ${cloudamqp.host}
    port: ${cloudamqp.port}
    password: ${cloudamqp.password}
    username: ${cloudamqp.username}
    virtual-host: ${cloudamqp.virtual-host}
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    test-connection: false
    username: ${SERVICE_MAIL_EMAIL}
    password: ${SERVICE_MAIL_PASSWORD}
    properties:
      mail:
        debug: ${SERVICE_MAIL_IS_DEBUG:false}
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: ${DISCOVERY_HOST}

management:
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

info:
  name: ${spring.application.name}
  version: '@project.version@'
  javaVersion: ${java.version}

# Custom properties
cloudamqp:
  host: ${CLOUDAMQP_HOST}
  port: ${CLOUDAMQP_PORT}
  password: ${CLOUDAMQP_PASSWORD}
  username: ${CLOUDAMQP_USERNAME}
  virtual-host: ${CLOUDAMQP_VIRTUAL_HOST}
  queue:
    send-template-mail: send-template-mail-queue

keycloak:
  issuer-uri: ${KEYCLOAK_ISSUER_URI}
  jwk-set-uri: ${KEYCLOAK_JWKS_URI}
  introspection-uri: ${KEYCLOAK_INTROSPECTION_ENDPOINT}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  jwt-converter:
    role-claims: realm_access.roles,resource_access.account.roles
    username-attribute: preferred_username

configuration:
  name: ${spring.application.name}
  email: ${SERVICE_MAIL_EMAIL}